version: '3.9'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  uicompanion-server:
    container_name: uicompanion-server
    depends_on:
      - mongodb
    build: ./packages/server
    restart: on-failure
    ports:
      - "3001:3001"
    environment:
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_PORT=$MONGODB_PORT
    
  uicompanion-client:
    container_name: uicompanion-client
    depends_on: 
      - uicompanion-server
    build: ./packages/app
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - LOG_LEVEL_IN_STRING=$LOG_LEVEL_IN_STRING
      - WEBHOOK_PROXY_URL=$WEBHOOK_PROXY_URL
      - APP_ID=$APP_ID
      - PRIVATE_KEY=$PRIVATE_KEY
      - WEBHOOK_SECRET=$WEBHOOK_SECRET
      - GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET