version: '3.9'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  uicompanion-server:
    container_name: uicompanion-server
    image: uicompanion-server
    depends_on:
      - mongodb
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_VERSION=18
        - APP_NAME=uicompanion-server
        - PORT=3001
    volumes:
      - ./apps/uicompanion-server:/app/apps/uicompanion-server
      - /app/apps/uicompanion-server/node_modules
    ports:
      - "3001:3001"
    environment:
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_PORT=$MONGODB_PORT
      - SERVER_BASE_URL=$SERVER_BASE_URL

  uicompanion-app:
    container_name: uicompanion-app
    image: uicompanion-app
    depends_on: 
      - uicompanion-server
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_VERSION=19
        - APP_NAME=uicompanion-app
        - PORT=3001
    volumes:
      - ./apps/uicompanion-app:/app/apps/uicompanion-app
      - /app/apps/uicompanion-app/node_modules
    ports:
      - "3000:3000"
    environment:
      - LOG_LEVEL_IN_STRING=$LOG_LEVEL_IN_STRING
      - LOG_LEVEL=$LOG_LEVEL
      - WEBHOOK_PROXY_URL=$WEBHOOK_PROXY_URL
      - APP_ID=$APP_ID
      - WEBHOOK_SECRET=$WEBHOOK_SECRET
      - GH_CLIENT_ID=$GH_CLIENT_ID
      - GH_CLIENT_SECRET=$GH_CLIENT_SECRET
      - PRIVATE_KEY=$PRIVATE_KEY