version: '3.9'
services:
  reverse-proxy:  
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=benedikt.geisberger@tum.de"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - ./mongo-data:/data/db

  uicompanion-server:
    container_name: uicompanion-server
    depends_on:
      - mongodb
    image: ghcr.io/bgeisb/uicompanionserver:latest
    restart: on-failure
    environment:
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`${SERVER_HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.services.server.loadbalancer.server.port=3000"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=letsencrypt"
    
  uicompanion-client:
    container_name: uicompanion-client
    depends_on: 
      - uicompanion-server
    image: ghcr.io/bgeisb/uicompanion:latest
    restart: on-failure
    environment:
      - LOG_LEVEL_IN_STRING=$LOG_LEVEL_IN_STRING
      - WEBHOOK_PROXY_URL=$WEBHOOK_PROXY_URL
      - APP_ID=$APP_ID
      - PRIVATE_KEY=$PRIVATE_KEY
      - WEBHOOK_SECRET=$WEBHOOK_SECRET
      - GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`${SERVER_HOST}`)"
      - "traefik.http.services.server.loadbalancer.server.port=3000"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=letsencrypt"