version: '3.9'
services:
  reverse-proxy:  
    image: traefik:v2.10
    command:
      # Docker configuration
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Configure entrypoint
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Global HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # SSL configuration
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=benedikt.geisberger@tum.de"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      # Enable dashboard
      - "--api.dashboard=true"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - ./mongo-data:/data/db

  uicompanion-server:
    container_name: uicompanion-server
    depends_on:
      - mongodb
      - reverse-proxy
    image: ghcr.io/ls1intum/uicompanion/uicompanion-server:${SERVER_IMAGE_TAG}
    restart: on-failure
    environment:
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`${HOST_ALIAS}`) && PathPrefix(`/api`)"
      - "traefik.http.services.server.loadbalancer.server.port=3001"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=letsencrypt"
    
  uicompanion-app:
    container_name: uicompanion-app
    depends_on: 
      - uicompanion-server
      - reverse-proxy
    image: ghcr.io/ls1intum/uicompanion/uicompanion-app:${APP_IMAGE_TAG}
    restart: on-failure
    environment:
      - LOG_LEVEL_IN_STRING=$LOG_LEVEL_IN_STRING
      - NODE_ENV=production
      - WEBHOOK_URL=$WEBHOOK_URL
      - APP_ID=$APP_ID
      - PRIVATE_KEY=$PRIVATE_KEY
      - WEBHOOK_SECRET=$WEBHOOK_SECRET
      - GH_CLIENT_ID=$GH_CLIENT_ID
      - GH_CLIENT_SECRET=$GH_CLIENT_SECRET
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`${HOST_ALIAS}`)"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"